name: CI

on: [push]

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                occ_version: [package]
                include:
                    - os: windows-latest
                      occ_version: 7.4.0
                    - os: windows-latest
                      occ_version: 7.5.0
                    - os: windows-latest
                      occ_version: 7.6.0
                exclude:
                    - os: windows-latest
                      occ_version: package

        runs-on: ${{matrix.os}}

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              path: 'source'
              fetch-depth: 0
              lfs: false

        - name: Cache Qt
          id: cache-qt
          uses: actions/cache@v1
          with:
              path: ../Qt
              key: ${{ runner.os }}-QtCache

        - name: Install Qt
          uses: jurplel/install-qt-action@v2
          with:
              cached: ${{ steps.cache-qt.outputs.cache-hit }}

